/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ERC20Capped__factory } from "./ERC20Capped__factory";
export { IERC20Metadata__factory } from "./IERC20Metadata__factory";
